### ISSUE TITLE
Disconnects from proxy server

### ISSUE THREAD

**Issue by mkunz7** [ryanchapman/go-any-proxy#21]
About every 12hrs or so we'll get a disconnect from our proxy server.
x.x.x.x is our proxy server

```
2016/03/13 23:50:02 any_proxy.go:375: : INFO : Added proxy server x.x.x.x:80
2016/03/13 23:50:02 any_proxy.go:339: : INFO : Listening for connections on [::]:3129
2016/03/13 23:55:02 any_proxy.go:509: : INFO : dial(): ERR: could not connect to x.x.x.x:80: dial tcp x.x.x.x:80: connection refused
2016/03/13 23:55:02 any_proxy.go:368: : INFO : Test connection to x.x.x.x:80: failed. Removing from proxy server list
2016/03/13 23:55:02 any_proxy.go:380: : INFO : None of the proxy servers specified are available. 
Exiting.
None of the proxy servers specified are available. 
Exiting.
2016/03/14 00:00:02 any_proxy.go:375: : INFO : Added proxy server x.x.x.x:80
2016/03/14 00:00:02 any_proxy.go:339: : INFO : Listening for connections on [::]:3129
2016/03/14 00:05:02 any_proxy.go:375: : INFO : Added proxy server x.x.x.x:80
2016/03/14 00:05:02 any_proxy.go:339: : INFO : Listening for connections on [::]:3129
```
Again I can't thank you enough for this project. With the latest fix this really has been able to change how we do a lot of different things here for the better. This is not a huge issue, just thought you should know.

**Comment by ryanchapman** [comment]
Hi,

Thanks and I'm glad that I could provide something that others find useful.  Every time I come across an issue that google can't solve, I try to publish my solution because I know others will come across the same thing.

For your issue, I'm starting to wonder if you have an unreliable network.  In #20, you reported seeing this: 

```2016/03/07 16:30:05 any_proxy.go:509: : INFO : dial(): ERR: could not connect to 10.0.7.214:443: dial tcp 10.0.7.214:443: no route to host```

which would indicate that your route disappeared.  Strange.

Can you a loop for 24 hours to see if pings are dropped to your 10.0.7.214 or x.x.x.x endpoints (x.x.x.x in the x.x.x.x:80 output above)?  Let me know if you need a loop syntax for bash(mac,linux)/powershell(win) and I'll see what I can do.

If you're interested in having any_proxy not quit when all upstreams are down and to just keep trying, I can probably add something to do that as well.

Ryan

**Comment by mkunz7** [comment]
I think that would be a good feature to aid in the stability of this program. We just have a script that watches it and reboots. I'll start a quick script that pings the main proxy to see if the link is going down. 10.0.7.214 is in a cloud environment that I wouldn't expect to stay up. I'll post the results later.

**Comment by ryanchapman** [comment]
@mkunz7 ,

You can use `-s=1` now to get the behavior you were looking for.

Ryan

**Comment by mkunz7** [comment]
Sorry it took so long. You were correct about the proxy losing connectivity. The fix works for the failing proxy.
