### ISSUE TITLE
Proxy HTTP requests

### ISSUE THREAD

**Issue by mrvne** [ryanchapman/go-any-proxy#31]
Not capable of HTTP (non TLS) requests? If so can this feature be added somehow?

**Comment by ryanchapman** [comment]
Usually people use squid for http proxying, mainly because it has more features. Can you tell me more about your use case?  Would squid work or is there a benefit to having it in any_proxy?  One benefit I can think of might be having one program to do both http and https proxying.  Although I don't necessarily want to duplicate the feature set of squid.

**Comment by ryanchapman** [comment]
Going to close this for now. Feel free to re-open if needed.
