### ISSUE TITLE
Use any-proxy as SMTP/IMAP forwarder

### ISSUE THREAD

**Issue by m-terlinde** [ryanchapman/go-any-proxy#35]
Hey Ryan,

I've read your blog post about any-proxy, but I'm quite not sure, if I can achieve my goal with your software.
Maybe you can help me out.

I have a server in a MZ which needs to send emails via SMTP and receive emails via IMAP. I have a satellite server in my DMZ which is able to talk to the correct MX server.

Can I simply forward any incoming traffic from the needed ports to my upstream server?

Cheers,
Matthias

**Comment by ryanchapman** [comment]
Hi Matthias,

any-proxy is designed for use cases where you don't have direct access to the internet and have to go through a proxy server like squid.  This is common in what I like to call "old school" corporations.  Doesn't sounds like your situation.

It's been a while since I managed a firewall.  In your case, you have two machines, "a server that needs to send emails via SMTP and receive email via IMAP" [server A] as well as a satellite server which can talk to the internet [server B].

I think I'd set the SMTP software on [server A] to relay mail to [server B].  Postfix calls that a relayhost.  Sendmail calls it a relay server.  For IMAP, on the firewall, I'd allow traffic from [server A] to internet hosts on dest port 993.

If I've misunderstood what you are trying to accomplish, please feel free to reopen this issue.

Ryan
